### ISSUE TITLE
sfdx dxb:profile:convert appears to cause problems for Case and CaseClose layout assignment permissions

### ISSUE THREAD

**Issue by hingchow94** [davidbrowaeys/DXB#12]
When I run `sfdx dxb:profile:convert`, it appears that only one of Case and CaseClose layout assignments are persisted. My guess is that layout assignment permissions are parsed based on record type. This works fine for every object except for Cases because Cases have layout assignments for both `Case` and `CaseClose` despite having the same record type.

Below is an example of valid metadata even though they both have the same `recordType`.
```
<layoutAssignments>
    <layout>Case-Case Layout</layout>
    <recordType>Case.Some_Record_Type</recordType>
</layoutAssignments>
<layoutAssignments>
    <layout>CaseClose-Close Case Layout</layout>
    <recordType>Case.Some_Record_Type</recordType>
</layoutAssignments>
```

Please let me know if you have any questions.

**Comment by davidbrowaeys** [comment]
Bloody CaseClose. Good pick up. Thank you @hingchow94

**Comment by OlivierBrabanders** [comment]
Closed by [PR 24](https://github.com/davidbrowaeys/DXB/pull/24) on release/2.0.0
