### ISSUE TITLE
sfdx dxb:profile:build appears to order permissions differently between Mac and Windows

### ISSUE THREAD

**Issue by hingchow94** [davidbrowaeys/DXB#6]
It appears that the `fs.readdirSync` function behaves inconsistently in terms of sorting as shown in these links:
https://stackoverflow.com/a/51890207/8797514
https://github.com/nodejs/node/issues/3232

This causes problems when running `sfdx dxb:profile:build` between developers who use different operating systems.

Is it possible to sort the arrays after calling `fs.readdirSync`, or allow this option by passing in an argument? Please let me know if you require more clarification.

**Comment by davidbrowaeys** [comment]
Thank you for pointing that out I have now made some change that will sort regardless of the operating system. Try version 1.7.7

**Comment by hingchow94** [comment]
It looks like this bug came back as part of 1.7.9 but I'm not quite sure why. Would you reopen this issue? Please let me know if you have any questions about this.

**Comment by davidbrowaeys** [comment]
@hingchow94  Thank you for raising this. I haven't touch that for a while though so could be something else, interesting. Let me investigate this again. Did you change anything on your side at all by any chance?

**Comment by davidbrowaeys** [comment]
Closing as the main defect got resolved
