### ISSUE TITLE
Test class names generated with comma

### ISSUE THREAD

**Issue by shreyagoyal06** [davidbrowaeys/DXB#65]
When using the dxb plugin in the yml and using the (sf dxb source fetchtest -x delta_manifest/package.xml) command, it generates the test classes names separated by comma but in the new SF command, the test class names need to be separated by space

<img width="693" alt="Screenshot 2024-09-20 at 7 23 14 PM" src="https://github.com/user-attachments/assets/c5610073-56f2-4a52-a21b-947c01005ecf">

With current script, getting below error in the pipeline:
AccountHandlerTest,AccountListControllerTest
(node:393) Warning: The previous version of this command used a comma-separated list for tests. We've changed how you specify multiple tests, so if you continue using your current syntax, your tests will probably not run as you expect.

If a test name contains a space, enclose it in double quotes.
For multiple test names, use one of the following formats:

- Repeat the flag for multiple test names: --tests Test1 --tests Test2 --tests "Test With Space"
- Separate the test names with spaces: --tests Test1 Test2 "Test With Space"

Can you please update the backend script according to latest sf command format?

**Comment by shreyagoyal06** [comment]
Hi @davidbrowaeys  

Hope you are doing well!

Can you please provide an explanation on the issue above?

Thanks,
Shreya Goyal

**Comment by davidbrowaeys** [comment]
@shreyagoyal06 Hello there, thank you for reaching out. I apologized for the lack of response. I have a new client very demanding :D and I have put this a bit on the side :( .

So with the migration to Salesforce cli 2.0, this is probably something we have not thought through quite yet. However the way we have done in AzureDevops is to split the output of the command by comma and then loop through to add the -t. 

cc: @OlivierBrabanders 

![image](https://github.com/user-attachments/assets/107fbfef-a276-49e4-9db4-530a1dce3d5e)

But what you are suggesting is probably simpler indeed, we could do it simply with space. We will work on that very shortly.

**Comment by shreyagoyal06** [comment]
Thanks @davidbrowaeys . If this fix is done at the backend itself, that would be the best.
Appreciate your time on this.
