### ISSUE TITLE
dxb:permissionset:clean fails with recordTypeVisibilities tags

### ISSUE THREAD

**Issue by cheokslee** [davidbrowaeys/DXB#7]
Running dxb:permissionset:clean fails on a permission set with recordTypeVisibilities tags with the following error:

TypeError: result.PermissionSet.recordTypeVisibilities.filter is not a function

**Comment by davidbrowaeys** [comment]
Thank Cheok, this is now fix in version 1.7.3. 
The issue was related to xml conversion to json. If one element only in meta file, it consider that as an object rather than an array
