### ISSUE TITLE
metadataRegistry

### ISSUE THREAD

**Issue by mshanemc** [davidbrowaeys/DXB#8]
I was poking around in here and saw this
https://github.com/davidbrowaeys/DXB/blob/ebb2ae6e3c9242d6adceedfb6ddc3ef95fc2b650/src/commands/dxb/source/delta.ts#L151

which seems like it's gonna be painful over time.

May I suggest seeing if something from here might be helpful?
https://github.com/forcedotcom/source-deploy-retrieve/blob/main/src/registry/metadataRegistry.json
https://github.com/forcedotcom/source-deploy-retrieve/blob/main/src/registry/registryAccess.ts

**Comment by davidbrowaeys** [comment]
That's a fantastic recommendation, so thoughtful of you. At the time I wrote my trigger a few years ago, I don't think that salesforce/source-deploy-retrieve existed. 

Thank you

**Comment by davidbrowaeys** [comment]
@mshanemc  thank you again for the suggestion, registry access is great. This is now available in version 1.7.6
